Fix quorum
rbkmoney/wb-list-manager pull request #25
Opened 2021-06-17 16:28 UTC by strug

2021-06-17 22:22 UTC, PospolitaNV commented on src/test/java/com/rbkmoney/wb/list/manager/RiakTest.java
> +        sleep(10000);
Как ты любишь долгие тесты))

2021-06-17 22:23 UTC, PospolitaNV requested changes
Сборка на тесте падает

2021-06-17 22:23 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/wb/list/manager/repository/ListRepository.java
> +                    .withOption(FetchValue.Option.R, Quorum.quorumQuorum())
Кворум кворум кворум кворум песенку поёёёт

2021-06-18 05:51 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/wb/list/manager/repository/ListRepository.java
> +                    .withOption(FetchValue.Option.R, Quorum.quorumQuorum())
https://www.youtube.com/watch?v=vrLu-gdkG6I

2021-06-20 07:20 UTC, strug commented
> Сборка на тесте падает

да это все риак, не умеет в ожидание поэтому и таймаут повесил, но все равно иногда флапает, порестартил билд прошел

2021-06-21 07:45 UTC, PospolitaNV approved these changes

2021-06-21 07:56 UTC, merged